version: '3'
vars:
  VIDEO_DOWNLOAD_URL_HD: https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/720/Big_Buck_Bunny_720_10s_1MB.mp4
  VIDEO_DOWNLOAD_URL_SD: https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/360/Big_Buck_Bunny_360_10s_1MB.mp4
  VIDEO_PATH: '{{.VIDEO_PATH | default "/tmp/video.mp4"}}'
  OUTPUT_PATH: '{{.OUTPUT_PATH | default "/dev/video10"}}'
tasks:
  getvideo:
    desc: "Get video in HD"
    cmds:
      - |
        wget -O {{.VIDEO_PATH}} {{.VIDEO_DOWNLOAD_URL_HD}} 
    silent: true

  getvideo:
    desc: "Get video in SD"
    cmds:
      - |
        wget -O {{.VIDEO_PATH}} {{.VIDEO_DOWNLOAD_URL_SD}} 
    silent: true

  run:
    desc: "Run stream"
    cmds:
      - |
        export GST_DEBUG=3
        python3 stream.py {{.VIDEO_PATH}} {{.OUTPUT_PATH}}
    silent: true

  install-v4l2loopback:
    desc: "install install-v4l2loopback (temporary to /dev/video10)"
    cmds:
      - |
        sudo modprobe v4l2loopback exclusive_caps=1 video_nr=10 card_label="v4l2loopback"

  build:
    desc: "setup venv"
    cmds:
      - |
        python3 -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

