[package]
name = "recorder"
version = "0.1.0"
edition = "2021"

[dependencies]
byte-slice-cast = "1.2.2"
gstreamer = "0.23.3"
gstreamer-app = "0.23.3"
futures = "0.3.31"
log = "0.4"
env_logger = "0.11"
chrono = "0.4"
serde = { version="1.0", features=["derive"] }
serde_json = "1.0"
toml = "0.8"
