# The main source pipeline that will be used to generate the video stream
source_pipeline_ = """videotestsrc is-live=true name=video-source \
            ! video/x-raw, format=YUY2,framerate=25/1, width=3840, height=2160 \
            ! queue \
            ! unixfdsink name=video-sink \
            """
source_pipeline = """v4l2src name=video-source device=/dev/video0 \
            ! videoconvert \
            ! timeoverlay \
            ! videoconvert \
            ! video/x-raw, format=YUY2 \
            ! queue \
            ! unixfdsink name=video-sink \
            """

# The pipeline that will be used to read the video stream from the source pipeline
# writes the video stream to a ts file and a frame to an appsink
#! video/x-raw, format=YUY2,framerate=25/1, width=3840, height=2160 \

recording_pipeline = """unixfdsrc name=video-source socket-path=/tmp/source-fd
            ! queue \
            ! tee name=t \
            t. \
            ! videoconvert \
            ! video/x-raw, format=NV12 \
            ! x264enc bitrate=20000 key-int-max=10 tune=zerolatency \
            ! h264parse config-interval=-1 \
            ! video/x-h264, stream-format=byte-stream \
            ! hlssink3 \
                name=video-sink \
                playlist-type=1 \
                target-duration=6 \
                enable-endlist=true \
                message-forward=true \
            t. \
            ! videoconvert \
            ! video/x-raw, format=BGR \
            ! videorate \
            ! video/x-raw, framerate=1/1 \
            ! videoscale \
            ! video/x-raw, width=720, height=480 \
            ! appsink name=frame-sink \
                async=false \
                sync=true \
                max-buffers=1 \
                drop=false \
                emit-signals=true
            """
still_pipeline = "unixfdsrc name=video-source ! queue ! videoconvert ! jpegenc snapshot=true ! queue ! filesink name=video-sink"
chunk_size = 6
output_dir = "."
chunk_prefix = "chunk"