#pipeline = """videotestsrc
#        ! videoconvert
#        ! fakesink"""

pipeline = """videotestsrc is-live=true
            ! video/x-raw, format=YUY2, width=3840, height=2160
            ! videoconvert
            ! queue
            ! timeoverlay
            ! x264enc key-int-max=10
            ! h264parse
            ! hlssink3 name=recording-sink playlist-type=1
            """

chunk_size = 6
output_dir = "."
chunk_prefix = "chunk"