# The main source pipeline that will be used to generate the video stream
source_pipeline = """v4l2src name=video-source device=/dev/video0 \
            ! queue \
            ! videoconvert \
            ! timeoverlay \
            ! videoconvert \
            ! video/x-raw, format=YUY2 \
            ! queue \
            ! unixfdsink name=video-sink \
            """

# This does not work with the unixfdsink element....
source_pipeline_ = """\
            glvideomixer name=mixer sink_0::zorder=1 sink_1::zorder=0 sink_0::alpha=1.0 sink_1::alpha=1.0 \
            ! gldownload \
            ! queue \
            ! videoconvert \
            ! video/x-raw \
            ! unixfdsink name=video-sink \
            wpesrc location="http://127.0.0.1:3000" name=wpesrc draw-background=0 \
            ! queue \
            ! glupload \
            ! mixer.sink_0 \
            v4l2src name=video-source device=/dev/video10 \
            ! queue \
            ! videoconvert \
            ! video/x-raw,format=YUY2,width=1920,height=1080 \
            ! queue \
            ! glupload \
            ! mixer.sink_1 \
            """

# The pipeline that will be used to read the video stream from the source pipeline
# writes the video stream to a ts file and a frame to an appsink
#! video/x-raw, format=YUY2,framerate=25/1, width=3840, height=2160 \

recording_pipeline = """unixfdsrc name=video-source socket-path=/tmp/source-fd
            ! queue \
            ! tee name=t \
            t. \
            ! videoconvert \
            ! video/x-raw, format=NV12 \
            ! x264enc bitrate=20000 key-int-max=10 tune=zerolatency \
            ! h264parse config-interval=-1 \
            ! video/x-h264, stream-format=byte-stream \
            ! hlssink3 \
                name=video-sink \
                playlist-type=1 \
                target-duration=6 \
                enable-endlist=true \
                message-forward=true \
            t. \
            ! videoconvert \
            ! video/x-raw, format=BGR \
            ! videorate \
            ! video/x-raw, framerate=1/1 \
            ! videoscale \
            ! video/x-raw, width=720, height=480 \
            ! appsink name=frame-sink \
                async=false \
                sync=true \
                max-buffers=1 \
                drop=false \
                emit-signals=true
            """
still_pipeline = "unixfdsrc name=video-source ! queue ! videoconvert ! jpegenc snapshot=true ! queue ! filesink name=video-sink"

preview_pipeline = """unixfdsrc name=video-source socket-path=/tmp/video0.sock \
            ! queue leaky=2 \
            ! videoconvert \
            ! videoscale \
            ! video/x-raw, width=1280, height=720 \
            ! videoconvert \
            ! x264enc bitrate=10000 key-int-max=10 tune=zerolatency \
            ! webrtcsink  run-signalling-server=true \
                run-web-server=true web-server-directory=client \
                async-handling=false \
                ice-transport-policy=all \
                name=video-sink
"""

preview_pipeline_overlay = """\
            glvideomixer name=mixer sink_0::zorder=1 sink_1::zorder=0 sink_0::alpha=1.0 sink_1::alpha=1.0 \
            ! gldownload \
            ! queue \
            ! videoconvert \
            ! videorate ! video/x-raw,framerate=30/1  \
            ! queue \
            ! x264enc bitrate=10000 key-int-max=10 tune=zerolatency \
            ! webrtcsink  run-signalling-server=true \
                run-web-server=true web-server-directory=client \
                async-handling=false \
                ice-transport-policy=all \
                name=video-sink            \
            wpesrc location="http://127.0.0.1:3000" name=wpesrc draw-background=0 \
            ! glupload \
            ! mixer.sink_0 \
            unixfdsrc name=video-source socket-path=/tmp/video10.sock \
            ! queue \
            ! videoconvert \
            ! video/x-raw,format=YUY2,width=1920,height=1080 \
            ! queue \
            ! glupload \
            ! mixer.sink_1
"""

chunk_size = 6
output_dir = "."
chunk_prefix = "chunk"