#pipeline = """videotestsrc
#        ! videoconvert
#        ! fakesink"""

pipeline = """videotestsrc is-live=true
            ! videoconvert
            ! queue
            ! timeoverlay
            ! x264enc key-int-max=10
            ! h264parse
            ! splitmuxsink name=recording-sink"""

chunk_size = 8
output_dir = "."
chunk_prefix = "chunk"