version: 3
includes:
  docker: 
    taskfile: ./docker/Taskfile.yml
    dir: ./docker
  endless-stream: 
    taskfile: ./tools/endless-stream/Taskfile.yml
    dir: ./tools/endless-stream
  overlay: 
    taskfile: ./tools/overlay-server/Taskfile.yml
    dir: ./tools/overlay-server
  command: ./tools/Taskfile.yml

tasks:
  build-app:
    desc: "Build app"
    cmds:
      - | 
        echo "Building app..."
        cargo build --release
