# https://taskfile.dev

version: '3'

vars:
  PORT: 3000
  VERSION: 1.0
tasks:
  build:
    desc: "Build overlay-server docker image"
    cmds:
      - |
        echo "{{.USER_WORKING_DIR}}"
        docker build -t recorder-overlay:{{.VERSION}} -f overlay-server.Dockerfile . 

  inspect:
    desc: "inspect container"
    cmds:
      - |
        docker run -it --rm --entrypoint /bin/sh recorder-overlay:1.0 
    silent: true
  run:
    desc: "Run overlay server"
    cmds:
      - |
        docker run \
        -d \
        --rm \
        -p {{.PORT}}:3000 \
        --name recorder-overlay \
        recorder-overlay:{{.VERSION}} 
