# https://taskfile.dev

version: '3'

tasks:
  start:
    desc: "Start streaming"
    cmds:
      - curl -X POST http://localhost:4000/start
    silent: true
  stop:
    desc: "Stop streaming"
    cmds:
      - curl -X POST http://localhost:4000/stop
    silent: true
